using ST10091324_PROG7312_Part1.Views;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;

namespace ST10091324_PROG7312_Part1.Model
{
    public class Incident
    {
        // The blueprint of the class was autogenerated by Visual Studio
        // and modified to fit our needs
        // Declaring fields for the incident report 
        public static int Counter { get; set; } = 01;

        [Key]
        public string Id { get; private set; }

        public string Location { get; private set; }

        public string Category { get; private set; }

        public string Description { get; private set; }

        public string MediaFilePath { get; private set; }

        // Foreign key to User
        public Guid UserId { get; set; }
        public User User { get; set; }  // Navigation property

        // Parameterless constructor for Entity Framework
        public Incident() { }

        public Incident(string location, string category, string description, string mediaFilePath)
        {
            // Assigning data passed to the fields belonging to the incident class
            Location = location;
            Category = category;
            Description = description;
            MediaFilePath = mediaFilePath;
            Id = generateId(location);
            Counter++;
        }

        private string generateId(string location)
        {
            // The code to get the first four characters of a string was taken from StackOverflow
            // Author: Habib
            // Link: https://stackoverflow.com/questions/15941985/how-to-get-the-first-five-character-of-a-string
            if (Location.Length == 1)
            {
                return $"{location.ToUpperInvariant()}000{Counter}";
            }
            else if (Location.Length == 2)
            {
                return $"{location.Substring(0, 2).ToUpperInvariant()}00{Counter}";
            }
            else if(Location.Length == 3)
            {
                return $"{location.Substring(0, 3).ToUpperInvariant()}0{Counter}";
            }
            else
            {
                return $"{location.Substring(0, 4).ToUpperInvariant()}{Counter}";
            }      
        }
    }
}
