using System;
using System.ComponentModel.DataAnnotations;

namespace ST10091324_PROG7312_Part1.Model
{
    public class LocalEvent
    {
        // The blueprint of the class was autogenerated by Visual Studio
        // and modified to fit our needs
        // Declaring fields for the events display 
        [Key]
        public int Id { get; set; }  // Primary key for LocalEvent

        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime Date { get; set; }
        public string ImageUrl { get; set; }
        public string Category { get; set; }
    }
}
