using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using System.Threading.Tasks;

namespace ST10091324_PROG7312_Part1.Model
{
    // Autogenerated by entity framework library/Visual Studio
    public class UserDbContext : DbContext
    {
        // Constructor specifies the connection string name in App.config or Web.config
        public UserDbContext() : base("name=UserDbContext")
        {
        }

        // DbSet represents the "Users" table in the database
        public DbSet<User> Users { get; set; }

        public DbSet<Incident> Incidents { get; set; }

        public DbSet<LocalEvent> LocalEvents { get; set; }

        public DbSet<ServiceRequest> ServiceRequests { get; set; }
    }
}
